<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net6.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\KeyPair.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MrAdvice" />
    <PackageReference Include="NLog" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\PackageIcon.png" Link="PackageIcon.png">
      <PackagePath></PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

</Project>
