<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net6.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\KeyPair.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <!--<ItemGroup>
    <PackageReference Include="MrAdvice" Version="2.16.0" />
    <PackageReference Include="NCrunch.Framework" Version="5.1.0" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="System.Threading.Channels" Version="8.0.0" />
  </ItemGroup>-->
  
  <ItemGroup>
    <ProjectReference Include="..\SimControl.Log\SimControl.Log.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="System.ServiceModel" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Update="Microsoft.VisualStudio.Threading.Analyzers" Version="17.11.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Update="Roslynator.Analyzers" Version="4.12.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Update="Roslynator.Formatting.Analyzers" Version="4.12.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Update="SonarAnalyzer.CSharp" Version="9.32.0.97167">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
