<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net480;net10.0</TargetFrameworks>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net480'">
    <Reference Include="System.ServiceModel" />
  </ItemGroup>

  <ItemGroup>
      <PackageReference Include="NUnit" />
      <PackageReference Include="NUnit.Analyzers">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="System.Threading.Channels" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimControl.Logging\SimControl.Logging.csproj" />
  </ItemGroup>

</Project>
