<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net480;net10.0</TargetFrameworks>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MrAdvice" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimControl.Logging\SimControl.Logging.csproj" />
    <ProjectReference Include="..\SimControl.Reactive\SimControl.Reactive.csproj" />
    <ProjectReference Include="..\SimControl.TestUtils\SimControl.TestUtils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\NLog.Tests.config" Link="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
