<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MrAdvice" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimControl.Logging\SimControl.Logging.csproj" />
  </ItemGroup>

</Project>
