<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net10.0-windows</TargetFrameworks>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MrAdvice" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit3TestAdapter">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimControl.Logging\SimControl.Logging.csproj" />
    <ProjectReference Include="..\SimControl.Reactive\SimControl.Reactive.csproj" />
    <ProjectReference Include="..\SimControl.Samples.CSharp.ClassLibrary\SimControl.Samples.CSharp.ClassLibrary.csproj" />
    <ProjectReference Include="..\SimControl.Samples.CSharp.ConsoleApp\SimControl.Samples.CSharp.ConsoleApp.csproj" />
    <ProjectReference Include="..\SimControl.Samples.CSharp.WcfClient\SimControl.Samples.CSharp.WcfClient.csproj" />
    <ProjectReference Include="..\SimControl.Samples.CSharp.WpfApp\SimControl.Samples.CSharp.WpfApp.csproj" />
    <ProjectReference Include="..\SimControl.TestUtils\SimControl.TestUtils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\NLog.IntegrationTests.config" Link="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
